/**
 * Regenerates the bundled node-type floor.
 *
 * The floor is what makes `npm install workflow-tester && workflow-tester run` work offline with
 * no setup. It is generated by the same harvest that serves
 * `workflow-tester node-types --version`, so there is no second implementation to drift:
 * if extraction is wrong, this is wrong too, and one set of tests catches both.
 *
 *   pnpm bundle:node-types [<n8n version>]
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { harvest } from '../packages/engine/src/node-types/harvest.js';
import { SUPPORTED_N8N_VERSION } from '../packages/engine/src/version.js';
import { fetchDescriptionDump, resolveLibraryVersion } from '../packages/instance/src/registry.js';

const app = process.argv[2] ?? SUPPORTED_N8N_VERSION;
const root = join(dirname(fileURLToPath(import.meta.url)), '..', 'packages', 'engine', 'bundled', app);

const libraryVersion = await resolveLibraryVersion(app);
const dump = await fetchDescriptionDump(libraryVersion);
const nodes = harvest(dump);

if (nodes.length === 0) {
  console.error(
    `n8n ${app}: harvested nothing from ${dump.length} descriptions — refusing to write an empty floor`,
  );
  process.exit(2);
}

mkdirSync(root, { recursive: true });
writeFileSync(
  join(root, 'meta.json'),
  `${JSON.stringify(
    {
      n8nVersion: app,
      libraryVersion,
      extractedAt: new Date().toISOString(),
      source: `n8n-nodes-base@${libraryVersion}`,
    },
    null,
    2,
  )}\n`,
);
// Stable key order and no indentation: this file is committed, and a reindented
// 200 KB blob is an unreviewable diff.
writeFileSync(join(root, 'nodes.json'), `${JSON.stringify(nodes)}\n`);

console.log(
  `n8n ${app} (n8n-nodes-base ${libraryVersion}): ${nodes.length} descriptions, ` +
    `${(Buffer.byteLength(JSON.stringify(nodes)) / 1024).toFixed(0)} KB`,
);
